name: Tag and DockerHub image generator

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  tag-release:
    runs-on: ubuntu-latest
    outputs:
      newtag: ${{ steps.mayorrelease.outputs.new_tag }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Fetch tags
        run: git fetch --tags --prune

      - name: Mayor release
        id: mayorrelease
        if: contains(github.event.pull_request.labels.*.name, 'minor update') == false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          current_tag=$(git describe --tags $(git rev-list --tags --max-count=1) | echo '0.0.0')
          echo "Current tag: $current_tag"
          echo "Mayor update"
          new_tag=$(echo "$current_tag" | awk -F. -v OFS=. '{print $1,$2+1,0}')
          echo "New tag: $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT
          git tag $new_tag
          git push origin $new_tag

      - name: Minor release
        if: contains(github.event.pull_request.labels.*.name, 'minor update')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          current_tag=$(git describe --tags $(git rev-list --tags --max-count=1) | echo '0.0.0')
          echo "Current tag: $current_tag"
          echo "Minor update"
          new_tag=$(echo "$current_tag" | awk -F. '{$NF = $NF + 1;} 1' OFS=.)
          echo "New tag: $new_tag"
          git tag $new_tag
          git push origin $new_tag

  dockerhub-update:
    needs: tag-release
    if: contains(github.event.pull_request.labels.*.name, 'minor update') == false
    runs-on: ubuntu-latest
    name: Push Docker image to Docker Hub
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: jkutkut/nginx-fileserver

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: jkutkut/nginx-fileserver:latest,jkutkut/nginx-fileserver:${{needs.tag-release.outputs.newtag}}
          labels: ${{ steps.meta.outputs.labels }}
